/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace RakNet {

using System;
using System.Runtime.InteropServices;

public class RakNetListRakNetSocket2 : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RakNetListRakNetSocket2(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(RakNetListRakNetSocket2 obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~RakNetListRakNetSocket2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RakNetPINVOKE.delete_RakNetListRakNetSocket2(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

    public RakNetSocket2 this[int index]  
    {  
        get   
        {
            return Get((uint)index); // use indexto retrieve and return another value.    
        }  
        set   
        {
            Replace(value, value, (uint)index, "Not used", 0);// use index and value to set the value somewhere.   
        }  
    } 

  public RakNetListRakNetSocket2() : this(RakNetPINVOKE.new_RakNetListRakNetSocket2__SWIG_0(), true) {
  }

  public RakNetListRakNetSocket2(RakNetListRakNetSocket2 original_copy) : this(RakNetPINVOKE.new_RakNetListRakNetSocket2__SWIG_1(RakNetListRakNetSocket2.getCPtr(original_copy)), true) {
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public RakNetListRakNetSocket2 CopyData(RakNetListRakNetSocket2 original_copy) {
    RakNetListRakNetSocket2 ret = new RakNetListRakNetSocket2(RakNetPINVOKE.RakNetListRakNetSocket2_CopyData(swigCPtr, RakNetListRakNetSocket2.getCPtr(original_copy)), false);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_RakNet__RakNetSocket2 Get(uint position) {
    SWIGTYPE_p_RakNet__RakNetSocket2 ret = new SWIGTYPE_p_RakNet__RakNetSocket2(RakNetPINVOKE.RakNetListRakNetSocket2_Get(swigCPtr, position), false);
    return ret;
  }

  public void Push(SWIGTYPE_p_RakNet__RakNetSocket2 input, string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Push(swigCPtr, SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(input), file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_RakNet__RakNetSocket2 Pop() {
    SWIGTYPE_p_RakNet__RakNetSocket2 ret = new SWIGTYPE_p_RakNet__RakNetSocket2(RakNetPINVOKE.RakNetListRakNetSocket2_Pop(swigCPtr), false);
    return ret;
  }

  public void Insert(SWIGTYPE_p_RakNet__RakNetSocket2 input, uint position, string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Insert__SWIG_0(swigCPtr, SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(input), position, file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Insert(SWIGTYPE_p_RakNet__RakNetSocket2 input, string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Insert__SWIG_1(swigCPtr, SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(input), file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Replace(SWIGTYPE_p_RakNet__RakNetSocket2 input, SWIGTYPE_p_RakNet__RakNetSocket2 filler, uint position, string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Replace__SWIG_0(swigCPtr, SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(input), SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(filler), position, file, line);
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Replace(SWIGTYPE_p_RakNet__RakNetSocket2 input) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Replace__SWIG_1(swigCPtr, SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(input));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAtIndex(uint position) {
    RakNetPINVOKE.RakNetListRakNetSocket2_RemoveAtIndex(swigCPtr, position);
  }

  public void RemoveAtIndexFast(uint position) {
    RakNetPINVOKE.RakNetListRakNetSocket2_RemoveAtIndexFast(swigCPtr, position);
  }

  public void RemoveFromEnd(uint num) {
    RakNetPINVOKE.RakNetListRakNetSocket2_RemoveFromEnd__SWIG_0(swigCPtr, num);
  }

  public void RemoveFromEnd() {
    RakNetPINVOKE.RakNetListRakNetSocket2_RemoveFromEnd__SWIG_1(swigCPtr);
  }

  public uint GetIndexOf(SWIGTYPE_p_RakNet__RakNetSocket2 input) {
    uint ret = RakNetPINVOKE.RakNetListRakNetSocket2_GetIndexOf(swigCPtr, SWIGTYPE_p_RakNet__RakNetSocket2.getCPtr(input));
    if (RakNetPINVOKE.SWIGPendingException.Pending) throw RakNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint Size() {
    uint ret = RakNetPINVOKE.RakNetListRakNetSocket2_Size(swigCPtr);
    return ret;
  }

  public void Clear(bool doNotDeallocateSmallBlocks, string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Clear(swigCPtr, doNotDeallocateSmallBlocks, file, line);
  }

  public void Preallocate(uint countNeeded, string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Preallocate(swigCPtr, countNeeded, file, line);
  }

  public void Compress(string file, uint line) {
    RakNetPINVOKE.RakNetListRakNetSocket2_Compress(swigCPtr, file, line);
  }

}

}
